import { PrismaClient, MuscleGroup, Equipment, Difficulty } from '@prisma/client';

const prisma = new PrismaClient();

const exercises = [
  // ─────────────── CHEST ───────────────
  {
    name: 'Barbell Bench Press',
    muscleGroup: MuscleGroup.CHEST,
    secondaryMuscles: JSON.stringify(['TRICEPS', 'SHOULDERS']),
    equipment: Equipment.GYM,
    difficulty: Difficulty.INTERMEDIATE,
    movementPattern: 'push',
    isCompound: true,
    contraindications: JSON.stringify(['SHOULDER_IMPINGEMENT']),
    coachingCues: JSON.stringify(['Retract shoulder blades and arch slightly', 'Grip just outside shoulder-width', 'Lower bar to lower chest with control', 'Drive feet into floor, press explosively']),
    demoUrl: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=500',
  },
  {
    name: 'Incline Barbell Press',
    muscleGroup: MuscleGroup.CHEST,
    secondaryMuscles: JSON.stringify(['SHOULDERS', 'TRICEPS']),
    equipment: Equipment.GYM,
    difficulty: Difficulty.INTERMEDIATE,
    movementPattern: 'push',
    isCompound: true,
    contraindications: JSON.stringify(['SHOULDER_IMPINGEMENT']),
    coachingCues: JSON.stringify(['Set bench to 30-45 degrees', 'Bar touches upper chest', 'Keep wrists stacked over elbows', 'Control descent, press with power']),
    demoUrl: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=500',
  },
  {
    name: 'Incline Dumbbell Press',
    muscleGroup: MuscleGroup.CHEST,
    secondaryMuscles: JSON.stringify(['SHOULDERS', 'TRICEPS']),
    equipment: Equipment.MINIMAL,
    difficulty: Difficulty.INTERMEDIATE,
    movementPattern: 'push',
    isCompound: true,
    contraindications: JSON.stringify(['SHOULDER_IMPINGEMENT']),
    coachingCues: JSON.stringify(['Set bench to 30-45 degree incline', 'Press dumbbells straight up, keeping wrists strong', 'Lower weights to sides of chest with control', 'Keep feet flat on floor for stability']),
    demoUrl: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=500',
  },
  {
    name: 'Flat Dumbbell Press',
    muscleGroup: MuscleGroup.CHEST,
    secondaryMuscles: JSON.stringify(['TRICEPS', 'SHOULDERS']),
    equipment: Equipment.MINIMAL,
    difficulty: Difficulty.BEGINNER,
    movementPattern: 'push',
    isCompound: true,
    contraindications: JSON.stringify(['SHOULDER_IMPINGEMENT']),
    coachingCues: JSON.stringify(['Lie flat, dumbbells at chest level', 'Press up and slightly inward', 'Squeeze chest at the top', 'Lower under control with slight arc']),
    demoUrl: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=500',
  },
  {
    name: 'Cable Chest Fly',
    muscleGroup: MuscleGroup.CHEST,
    secondaryMuscles: JSON.stringify(['SHOULDERS']),
    equipment: Equipment.GYM,
    difficulty: Difficulty.BEGINNER,
    movementPattern: 'isolation',
    isCompound: false,
    contraindications: JSON.stringify([]),
    coachingCues: JSON.stringify(['Set cables at shoulder height', 'Slight bend in elbows throughout', 'Bring hands together in front of chest', 'Squeeze and hold for 1 second at peak']),
    demoUrl: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=500',
  },
  {
    name: 'Dumbbell Chest Fly',
    muscleGroup: MuscleGroup.CHEST,
    secondaryMuscles: JSON.stringify(['SHOULDERS']),
    equipment: Equipment.MINIMAL,
    difficulty: Difficulty.BEGINNER,
    movementPattern: 'isolation',
    isCompound: false,
    contraindications: JSON.stringify(['SHOULDER_IMPINGEMENT']),
    coachingCues: JSON.stringify(['Lie flat, arms out wide with slight bend', 'Arc dumbbells together like hugging a barrel', 'Squeeze chest at top', 'Stretch at the bottom']),
    demoUrl: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=500',
  },
  {
    name: 'Bodyweight Push-Up',
    muscleGroup: MuscleGroup.CHEST,
    secondaryMuscles: JSON.stringify(['TRICEPS', 'SHOULDERS', 'ABS']),
    equipment: Equipment.HOME,
    difficulty: Difficulty.BEGINNER,
    movementPattern: 'push',
    isCompound: true,
    contraindications: JSON.stringify(['WRIST_PAIN']),
    coachingCues: JSON.stringify(['Hands slightly wider than shoulder width', 'Keep body in a straight line from head to heels', 'Lower chest to the floor, elbows at 45 degrees', 'Push away from the floor aggressively']),
    demoUrl: 'https://images.unsplash.com/photo-1598971639058-fab3c3109a00?w=500',
  },
  {
    name: 'Wide Push-Up',
    muscleGroup: MuscleGroup.CHEST,
    secondaryMuscles: JSON.stringify(['SHOULDERS', 'TRICEPS']),
    equipment: Equipment.HOME,
    difficulty: Difficulty.BEGINNER,
    movementPattern: 'push',
    isCompound: true,
    contraindications: JSON.stringify(['WRIST_PAIN', 'SHOULDER_IMPINGEMENT']),
    coachingCues: JSON.stringify(['Place hands wider than shoulder-width', 'Elbows flare slightly outward', 'Emphasizes outer chest', 'Keep core rigid throughout']),
    demoUrl: 'https://images.unsplash.com/photo-1598971639058-fab3c3109a00?w=500',
  },
  {
    name: 'Chest Dip',
    muscleGroup: MuscleGroup.CHEST,
    secondaryMuscles: JSON.stringify(['TRICEPS', 'SHOULDERS']),
    equipment: Equipment.GYM,
    difficulty: Difficulty.INTERMEDIATE,
    movementPattern: 'push',
    isCompound: true,
    contraindications: JSON.stringify(['SHOULDER_IMPINGEMENT', 'WRIST_PAIN']),
    coachingCues: JSON.stringify(['Lean torso slightly forward to bias chest', 'Lower until upper arms are parallel to floor', 'Keep elbows slightly flared', 'Press up with chest and triceps']),
    demoUrl: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=500',
  },
  {
    name: 'DB Floor Press',
    muscleGroup: MuscleGroup.CHEST,
    secondaryMuscles: JSON.stringify(['TRICEPS']),
    equipment: Equipment.MINIMAL,
    difficulty: Difficulty.BEGINNER,
    movementPattern: 'push',
    isCompound: true,
    contraindications: JSON.stringify([]),
    coachingCues: JSON.stringify(['Lie on floor, knees bent', 'Dumbbells at chest level, press up', 'Floor limits range of motion — safe for shoulders', 'Control the descent to floor']),
    demoUrl: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=500',
  },

  // ─────────────── BACK ───────────────
  {
    name: 'Barbell Bent-Over Row',
    muscleGroup: MuscleGroup.BACK,
    secondaryMuscles: JSON.stringify(['BICEPS', 'SHOULDERS', 'HAMSTRINGS']),
    equipment: Equipment.GYM,
    difficulty: Difficulty.INTERMEDIATE,
    movementPattern: 'pull',
    isCompound: true,
    contraindications: JSON.stringify(['ACUTE_LOWER_BACK_PAIN']),
    coachingCues: JSON.stringify(['Hinge at hips, back flat, torso 45 degrees', 'Pull bar to lower chest / upper abdomen', 'Squeeze shoulder blades at top', 'Lower bar under control']),
    demoUrl: 'https://images.unsplash.com/photo-1605296867304-46d5465a25f1?w=500',
  },
  {
    name: 'Seated Cable Row',
    muscleGroup: MuscleGroup.BACK,
    secondaryMuscles: JSON.stringify(['BICEPS', 'SHOULDERS']),
    equipment: Equipment.GYM,
    difficulty: Difficulty.BEGINNER,
    movementPattern: 'pull',
    isCompound: true,
    contraindications: JSON.stringify([]),
    coachingCues: JSON.stringify(['Sit tall with slight lean back', 'Pull handle to belly button', 'Squeeze shoulder blades together', 'Return slowly, feel the stretch']),
    demoUrl: 'https://images.unsplash.com/photo-1605296867304-46d5465a25f1?w=500',
  },
  {
    name: 'Lat Pulldown',
    muscleGroup: MuscleGroup.BACK,
    secondaryMuscles: JSON.stringify(['BICEPS']),
    equipment: Equipment.GYM,
    difficulty: Difficulty.BEGINNER,
    movementPattern: 'pull',
    isCompound: true,
    contraindications: JSON.stringify([]),
    coachingCues: JSON.stringify(['Grip the bar slightly wider than shoulder-width', 'Pull the bar down to your upper chest, leaning slightly back', 'Squeeze shoulder blades together at the bottom', 'Let the bar return slowly to the starting position']),
    demoUrl: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=500',
  },
  {
    name: 'Pull-Up',
    muscleGroup: MuscleGroup.BACK,
    secondaryMuscles: JSON.stringify(['BICEPS', 'ABS']),
    equipment: Equipment.GYM,
    difficulty: Difficulty.ADVANCED,
    movementPattern: 'pull',
    isCompound: true,
    contraindications: JSON.stringify(['SHOULDER_IMPINGEMENT']),
    coachingCues: JSON.stringify(['Hang with full grip, shoulders packed', 'Pull chest to bar leading with elbows', 'Full ROM — dead hang to chin over bar', 'Lower under control']),
    demoUrl: 'https://images.unsplash.com/photo-1605296867304-46d5465a25f1?w=500',
  },
  {
    name: 'Assisted Pull-Up',
    muscleGroup: MuscleGroup.BACK,
    secondaryMuscles: JSON.stringify(['BICEPS']),
    equipment: Equipment.GYM,
    difficulty: Difficulty.BEGINNER,
    movementPattern: 'pull',
    isCompound: true,
    contraindications: JSON.stringify([]),
    coachingCues: JSON.stringify(['Use assisted machine or band', 'Focus on pulling elbows down and back', 'Squeeze lat at bottom of rep', 'Lower slowly even with assistance']),
    demoUrl: 'https://images.unsplash.com/photo-1605296867304-46d5465a25f1?w=500',
  },
  {
    name: 'T-Bar Row',
    muscleGroup: MuscleGroup.BACK,
    secondaryMuscles: JSON.stringify(['BICEPS', 'SHOULDERS']),
    equipment: Equipment.GYM,
    difficulty: Difficulty.INTERMEDIATE,
    movementPattern: 'pull',
    isCompound: true,
    contraindications: JSON.stringify(['ACUTE_LOWER_BACK_PAIN']),
    coachingCues: JSON.stringify(['Straddle bar, grip handle', 'Keep back flat, pull to lower chest', 'Strong squeeze at top', 'Control the descent']),
    demoUrl: 'https://images.unsplash.com/photo-1605296867304-46d5465a25f1?w=500',
  },
  {
    name: 'Chest-Supported DB Row',
    muscleGroup: MuscleGroup.BACK,
    secondaryMuscles: JSON.stringify(['BICEPS', 'SHOULDERS']),
    equipment: Equipment.MINIMAL,
    difficulty: Difficulty.BEGINNER,
    movementPattern: 'pull',
    isCompound: true,
    contraindications: JSON.stringify([]),
    coachingCues: JSON.stringify(['Lie face-down on incline bench', 'Pull dumbbells up to armpits', 'Takes lower back out of equation', 'Full stretch at the bottom']),
    demoUrl: 'https://images.unsplash.com/photo-1605296867304-46d5465a25f1?w=500',
  },
  {
    name: 'Dumbbell One-Arm Row',
    muscleGroup: MuscleGroup.BACK,
    secondaryMuscles: JSON.stringify(['BICEPS', 'SHOULDERS']),
    equipment: Equipment.MINIMAL,
    difficulty: Difficulty.BEGINNER,
    movementPattern: 'pull',
    isCompound: true,
    contraindications: JSON.stringify([]),
    coachingCues: JSON.stringify(['Place opposite hand and knee on a bench', 'Pull dumbbell up to hip level, leading with the elbow', 'Keep your back flat and parallel to the bench', 'Lower the dumbbell under control, stretching the lat']),
    demoUrl: 'https://images.unsplash.com/photo-1605296867424-35fc25c9212a?w=500',
  },
  {
    name: 'Banded Lat Pulldown',
    muscleGroup: MuscleGroup.BACK,
    secondaryMuscles: JSON.stringify(['BICEPS', 'SHOULDERS']),
    equipment: Equipment.HOME,
    difficulty: Difficulty.BEGINNER,
    movementPattern: 'pull',
    isCompound: true,
    contraindications: JSON.stringify([]),
    coachingCues: JSON.stringify(['Anchor resistance band overhead', 'Kneel or sit, pull band down towards upper chest', 'Squeeze shoulder blades together', 'Extend arms back up slowly under control']),
    demoUrl: 'https://images.unsplash.com/photo-1598971639058-fab3c3109a00?w=500',
  },
  {
    name: 'Inverted Row (Table Row)',
    muscleGroup: MuscleGroup.BACK,
    secondaryMuscles: JSON.stringify(['BICEPS', 'ABS']),
    equipment: Equipment.HOME,
    difficulty: Difficulty.BEGINNER,
    movementPattern: 'pull',
    isCompound: true,
    contraindications: JSON.stringify([]),
    coachingCues: JSON.stringify(['Lie under a table, grip the edge', 'Keep body straight, pull chest to table', 'Squeeze shoulder blades at top', 'Lower under control']),
    demoUrl: 'https://images.unsplash.com/photo-1598971639058-fab3c3109a00?w=500',
  },
  {
    name: 'Straight-Arm Pulldown',
    muscleGroup: MuscleGroup.BACK,
    secondaryMuscles: JSON.stringify(['ABS']),
    equipment: Equipment.GYM,
    difficulty: Difficulty.BEGINNER,
    movementPattern: 'isolation',
    isCompound: false,
    contraindications: JSON.stringify([]),
    coachingCues: JSON.stringify(['Slight bend in elbows throughout', 'Pull bar from overhead to thighs', 'Feel the lat stretch fully at top', 'Squeeze lat hard at bottom']),
    demoUrl: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=500',
  },

  // ─────────────── SHOULDERS ───────────────
  {
    name: 'Barbell Overhead Press',
    muscleGroup: MuscleGroup.SHOULDERS,
    secondaryMuscles: JSON.stringify(['TRICEPS', 'ABS']),
    equipment: Equipment.GYM,
    difficulty: Difficulty.INTERMEDIATE,
    movementPattern: 'push',
    isCompound: true,
    contraindications: JSON.stringify(['SHOULDER_IMPINGEMENT']),
    coachingCues: JSON.stringify(['Grip just outside shoulders', 'Press bar overhead in straight line', 'Squeeze glutes and brace core', 'Lock out fully at top']),
    demoUrl: 'https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?w=500',
  },
  {
    name: 'Dumbbell Shoulder Press',
    muscleGroup: MuscleGroup.SHOULDERS,
    secondaryMuscles: JSON.stringify(['TRICEPS']),
    equipment: Equipment.MINIMAL,
    difficulty: Difficulty.BEGINNER,
    movementPattern: 'push',
    isCompound: true,
    contraindications: JSON.stringify(['SHOULDER_IMPINGEMENT']),
    coachingCues: JSON.stringify(['Sit or stand tall, dumbbells at shoulder height', 'Press dumbbells straight up, keeping core tight', 'Keep elbows slightly tucked (in the scapular plane)', 'Lower under control to start position']),
    demoUrl: 'https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?w=500',
  },
  {
    name: 'Arnold Press',
    muscleGroup: MuscleGroup.SHOULDERS,
    secondaryMuscles: JSON.stringify(['TRICEPS']),
    equipment: Equipment.MINIMAL,
    difficulty: Difficulty.INTERMEDIATE,
    movementPattern: 'push',
    isCompound: true,
    contraindications: JSON.stringify(['SHOULDER_IMPINGEMENT']),
    coachingCues: JSON.stringify(['Start with palms facing you at chin height', 'Rotate palms outward as you press up', 'Full rotation at the top', 'Reverse the motion on descent']),
    demoUrl: 'https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?w=500',
  },
  {
    name: 'Dumbbell Lateral Raise',
    muscleGroup: MuscleGroup.SHOULDERS,
    secondaryMuscles: JSON.stringify([]),
    equipment: Equipment.MINIMAL,
    difficulty: Difficulty.BEGINNER,
    movementPattern: 'isolation',
    isCompound: false,
    contraindications: JSON.stringify(['SHOULDER_IMPINGEMENT']),
    coachingCues: JSON.stringify(['Slight bend in elbows', 'Raise arms to shoulder height', 'Lead with elbows, not wrists', 'Lower slowly for 3 seconds']),
    demoUrl: 'https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?w=500',
  },
  {
    name: 'Cable Lateral Raise',
    muscleGroup: MuscleGroup.SHOULDERS,
    secondaryMuscles: JSON.stringify([]),
    equipment: Equipment.GYM,
    difficulty: Difficulty.BEGINNER,
    movementPattern: 'isolation',
    isCompound: false,
    contraindications: JSON.stringify(['SHOULDER_IMPINGEMENT']),
    coachingCues: JSON.stringify(['Cable at lowest setting', 'Cross body to grab handle', 'Raise arm to shoulder height', 'Constant tension throughout']),
    demoUrl: 'https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?w=500',
  },
  {
    name: 'Face Pull',
    muscleGroup: MuscleGroup.SHOULDERS,
    secondaryMuscles: JSON.stringify(['BACK']),
    equipment: Equipment.GYM,
    difficulty: Difficulty.BEGINNER,
    movementPattern: 'pull',
    isCompound: false,
    contraindications: JSON.stringify([]),
    coachingCues: JSON.stringify(['Cable at forehead height', 'Pull rope toward face, elbows high and wide', 'External rotate at end — hands behind ears', 'Control the return']),
    demoUrl: 'https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?w=500',
  },
  {
    name: 'Band Pull-Apart',
    muscleGroup: MuscleGroup.SHOULDERS,
    secondaryMuscles: JSON.stringify(['BACK']),
    equipment: Equipment.HOME,
    difficulty: Difficulty.BEGINNER,
    movementPattern: 'pull',
    isCompound: false,
    contraindications: JSON.stringify([]),
    coachingCues: JSON.stringify(['Hold band at shoulder height', 'Pull band apart to chest level', 'Squeeze shoulder blades together', 'Control the return']),
    demoUrl: 'https://images.unsplash.com/photo-1598971639058-fab3c3109a00?w=500',
  },

  // ─────────────── BICEPS ───────────────
  {
    name: 'Barbell Curl',
    muscleGroup: MuscleGroup.BICEPS,
    secondaryMuscles: JSON.stringify(['FOREARMS']),
    equipment: Equipment.GYM,
    difficulty: Difficulty.BEGINNER,
    movementPattern: 'isolation',
    isCompound: false,
    contraindications: JSON.stringify(['ELBOW_PAIN']),
    coachingCues: JSON.stringify(['Elbows stay at sides', 'Curl bar to chin level', 'Supinate wrists at top', 'Lower slowly with control']),
    demoUrl: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=500',
  },
  {
    name: 'Dumbbell Bicep Curl',
    muscleGroup: MuscleGroup.BICEPS,
    secondaryMuscles: JSON.stringify([]),
    equipment: Equipment.MINIMAL,
    difficulty: Difficulty.BEGINNER,
    movementPattern: 'isolation',
    isCompound: false,
    contraindications: JSON.stringify(['ELBOW_PAIN']),
    coachingCues: JSON.stringify(['Alternate or simultaneous', 'Full supination at the top', 'No swinging or body rocking', 'Squeeze hard at the top']),
    demoUrl: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=500',
  },
  {
    name: 'Dumbbell Hammer Curl',
    muscleGroup: MuscleGroup.BICEPS,
    secondaryMuscles: JSON.stringify([]),
    equipment: Equipment.MINIMAL,
    difficulty: Difficulty.BEGINNER,
    movementPattern: 'isolation',
    isCompound: false,
    contraindications: JSON.stringify([]),
    coachingCues: JSON.stringify(['Stand tall, palms facing each other', 'Keep elbows glued to sides', 'Curl dumbbells up without swinging your upper body', 'Lower slowly, squeezing the tricep at the bottom']),
    demoUrl: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=500',
  },
  {
    name: 'Cable Bicep Curl',
    muscleGroup: MuscleGroup.BICEPS,
    secondaryMuscles: JSON.stringify([]),
    equipment: Equipment.GYM,
    difficulty: Difficulty.BEGINNER,
    movementPattern: 'isolation',
    isCompound: false,
    contraindications: JSON.stringify(['ELBOW_PAIN']),
    coachingCues: JSON.stringify(['Constant tension with cable', 'Full ROM from extension to contraction', 'Squeeze at top', 'Don\'t let elbows drift forward']),
    demoUrl: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=500',
  },
  {
    name: 'Preacher Curl',
    muscleGroup: MuscleGroup.BICEPS,
    secondaryMuscles: JSON.stringify([]),
    equipment: Equipment.GYM,
    difficulty: Difficulty.INTERMEDIATE,
    movementPattern: 'isolation',
    isCompound: false,
    contraindications: JSON.stringify(['ELBOW_PAIN']),
    coachingCues: JSON.stringify(['Chest against pad, no cheating', 'Full stretch at the bottom', 'Curl to full contraction', 'Lower very slowly']),
    demoUrl: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=500',
  },
  {
    name: 'Resistance Band Curl',
    muscleGroup: MuscleGroup.BICEPS,
    secondaryMuscles: JSON.stringify([]),
    equipment: Equipment.HOME,
    difficulty: Difficulty.BEGINNER,
    movementPattern: 'isolation',
    isCompound: false,
    contraindications: JSON.stringify([]),
    coachingCues: JSON.stringify(['Step on band, grip handles', 'Curl hands to shoulders', 'Squeeze bicep at top', 'Lower slowly with resistance']),
    demoUrl: 'https://images.unsplash.com/photo-1598971639058-fab3c3109a00?w=500',
  },

  // ─────────────── TRICEPS ───────────────
  {
    name: 'Cable Tricep Pushdown',
    muscleGroup: MuscleGroup.TRICEPS,
    secondaryMuscles: JSON.stringify([]),
    equipment: Equipment.GYM,
    difficulty: Difficulty.BEGINNER,
    movementPattern: 'isolation',
    isCompound: false,
    contraindications: JSON.stringify(['ELBOW_PAIN']),
    coachingCues: JSON.stringify(['Elbows pinned at sides', 'Push bar down to full extension', 'Squeeze tricep at bottom', 'Control the return']),
    demoUrl: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=500',
  },
  {
    name: 'Skull Crusher',
    muscleGroup: MuscleGroup.TRICEPS,
    secondaryMuscles: JSON.stringify([]),
    equipment: Equipment.GYM,
    difficulty: Difficulty.INTERMEDIATE,
    movementPattern: 'isolation',
    isCompound: false,
    contraindications: JSON.stringify(['ELBOW_PAIN']),
    coachingCues: JSON.stringify(['Lie on bench, bar over forehead', 'Keep elbows pointing up, lower bar to forehead', 'Extend fully at top', 'Slow and controlled throughout']),
    demoUrl: 'https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?w=500',
  },
  {
    name: 'Tricep Dumbbell Overhead Extension',
    muscleGroup: MuscleGroup.TRICEPS,
    secondaryMuscles: JSON.stringify([]),
    equipment: Equipment.MINIMAL,
    difficulty: Difficulty.BEGINNER,
    movementPattern: 'isolation',
    isCompound: false,
    contraindications: JSON.stringify(['ELBOW_PAIN']),
    coachingCues: JSON.stringify(['Sit or stand tall, hold one dumbbell with both hands overhead', 'Bend elbows to lower weight behind your head', 'Keep elbows pointing forward, not flared out', 'Extend arms straight up, squeezing the triceps']),
    demoUrl: 'https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?w=500',
  },
  {
    name: 'Tricep Kickback',
    muscleGroup: MuscleGroup.TRICEPS,
    secondaryMuscles: JSON.stringify([]),
    equipment: Equipment.MINIMAL,
    difficulty: Difficulty.BEGINNER,
    movementPattern: 'isolation',
    isCompound: false,
    contraindications: JSON.stringify([]),
    coachingCues: JSON.stringify(['Hinge forward, upper arm parallel to floor', 'Extend forearm back to full lock-out', 'Squeeze tricep hard at extension', 'Lower slowly back to 90 degrees']),
    demoUrl: 'https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?w=500',
  },
  {
    name: 'Diamond Push-Up',
    muscleGroup: MuscleGroup.TRICEPS,
    secondaryMuscles: JSON.stringify(['CHEST']),
    equipment: Equipment.HOME,
    difficulty: Difficulty.INTERMEDIATE,
    movementPattern: 'push',
    isCompound: true,
    contraindications: JSON.stringify(['WRIST_PAIN', 'ELBOW_PAIN']),
    coachingCues: JSON.stringify(['Hands close together forming a diamond', 'Elbows track backward, not outward', 'Lower chest to hands', 'Full extension at top']),
    demoUrl: 'https://images.unsplash.com/photo-1598971639058-fab3c3109a00?w=500',
  },
  {
    name: 'Band Tricep Pushdown',
    muscleGroup: MuscleGroup.TRICEPS,
    secondaryMuscles: JSON.stringify([]),
    equipment: Equipment.HOME,
    difficulty: Difficulty.BEGINNER,
    movementPattern: 'isolation',
    isCompound: false,
    contraindications: JSON.stringify([]),
    coachingCues: JSON.stringify(['Anchor band above head', 'Elbows pinned at sides', 'Push band down to full extension', 'Squeeze tricep hard']),
    demoUrl: 'https://images.unsplash.com/photo-1598971639058-fab3c3109a00?w=500',
  },

  // ─────────────── QUADS ───────────────
  {
    name: 'Barbell Back Squat',
    muscleGroup: MuscleGroup.QUADS,
    secondaryMuscles: JSON.stringify(['GLUTES', 'HAMSTRINGS', 'ABS']),
    equipment: Equipment.GYM,
    difficulty: Difficulty.INTERMEDIATE,
    movementPattern: 'squat',
    isCompound: true,
    contraindications: JSON.stringify(['SEVERE_KNEE_PAIN', 'ACUTE_LOWER_BACK_PAIN']),
    coachingCues: JSON.stringify(['Bar on upper traps, brace core', 'Feet shoulder-width, toes slightly out', 'Break at hips and knees simultaneously', 'Drive through heels, chest up']),
    demoUrl: 'https://images.unsplash.com/photo-1574680096145-d05b474e2155?w=500',
  },
  {
    name: 'Leg Press',
    muscleGroup: MuscleGroup.QUADS,
    secondaryMuscles: JSON.stringify(['GLUTES', 'HAMSTRINGS']),
    equipment: Equipment.GYM,
    difficulty: Difficulty.BEGINNER,
    movementPattern: 'squat',
    isCompound: true,
    contraindications: JSON.stringify(['SEVERE_KNEE_PAIN']),
    coachingCues: JSON.stringify(['Feet hip-width, mid-platform', 'Lower until knees at 90 degrees', 'Never lock knees explosively', 'Drive through full foot']),
    demoUrl: 'https://images.unsplash.com/photo-1574680096145-d05b474e2155?w=500',
  },
  {
    name: 'Leg Extension',
    muscleGroup: MuscleGroup.QUADS,
    secondaryMuscles: JSON.stringify([]),
    equipment: Equipment.GYM,
    difficulty: Difficulty.BEGINNER,
    movementPattern: 'isolation',
    isCompound: false,
    contraindications: JSON.stringify(['SEVERE_KNEE_PAIN']),
    coachingCues: JSON.stringify(['Full extension at top', 'Squeeze quad hard for 1 second', 'Lower slowly — 3 second descent', 'Keep hips stable']),
    demoUrl: 'https://images.unsplash.com/photo-1574680096145-d05b474e2155?w=500',
  },
  {
    name: 'Hack Squat',
    muscleGroup: MuscleGroup.QUADS,
    secondaryMuscles: JSON.stringify(['GLUTES', 'HAMSTRINGS']),
    equipment: Equipment.GYM,
    difficulty: Difficulty.INTERMEDIATE,
    movementPattern: 'squat',
    isCompound: true,
    contraindications: JSON.stringify(['SEVERE_KNEE_PAIN']),
    coachingCues: JSON.stringify(['Feet low on platform for quad bias', 'Lower to 90 degrees or below', 'Drive through heels', 'Keep chest against pad']),
    demoUrl: 'https://images.unsplash.com/photo-1574680096145-d05b474e2155?w=500',
  },
  {
    name: 'Goblet Squat',
    muscleGroup: MuscleGroup.QUADS,
    secondaryMuscles: JSON.stringify(['GLUTES', 'HAMSTRINGS', 'ABS']),
    equipment: Equipment.MINIMAL,
    difficulty: Difficulty.BEGINNER,
    movementPattern: 'squat',
    isCompound: true,
    contraindications: JSON.stringify(['SEVERE_KNEE_PAIN']),
    coachingCues: JSON.stringify(['Hold the weight close to your chest', 'Keep your chest tall and eyes forward', 'Squat down until thighs are parallel to ground', 'Drive through your heels to stand up']),
    demoUrl: 'https://images.unsplash.com/photo-1574680096145-d05b474e2155?w=500',
  },
  {
    name: 'Bulgarian Split Squat',
    muscleGroup: MuscleGroup.QUADS,
    secondaryMuscles: JSON.stringify(['GLUTES', 'HAMSTRINGS']),
    equipment: Equipment.HOME,
    difficulty: Difficulty.INTERMEDIATE,
    movementPattern: 'lunge',
    isCompound: true,
    contraindications: JSON.stringify(['SEVERE_KNEE_PAIN']),
    coachingCues: JSON.stringify(['Place back foot flat on a bench or chair', 'Keep torso upright, lower hips straight down', 'Front knee should stay aligned over toes', 'Drive through front heel to return to top']),
    demoUrl: 'https://images.unsplash.com/photo-1574680096145-d05b474e2155?w=500',
  },
  {
    name: 'Walking Lunge',
    muscleGroup: MuscleGroup.QUADS,
    secondaryMuscles: JSON.stringify(['GLUTES', 'HAMSTRINGS']),
    equipment: Equipment.HOME,
    difficulty: Difficulty.BEGINNER,
    movementPattern: 'lunge',
    isCompound: true,
    contraindications: JSON.stringify(['SEVERE_KNEE_PAIN']),
    coachingCues: JSON.stringify(['Step forward, lower back knee to floor', 'Keep torso upright', 'Push off front foot to step through', 'Alternate legs as you walk']),
    demoUrl: 'https://images.unsplash.com/photo-1574680096145-d05b474e2155?w=500',
  },
  {
    name: 'Sissy Squat',
    muscleGroup: MuscleGroup.QUADS,
    secondaryMuscles: JSON.stringify([]),
    equipment: Equipment.HOME,
    difficulty: Difficulty.ADVANCED,
    movementPattern: 'squat',
    isCompound: false,
    contraindications: JSON.stringify(['SEVERE_KNEE_PAIN']),
    coachingCues: JSON.stringify(['Hold support, rise on toes', 'Lean back as knees track forward', 'Lower until knees near floor', 'Drive back up squeezing quads']),
    demoUrl: 'https://images.unsplash.com/photo-1574680096145-d05b474e2155?w=500',
  },

  // ─────────────── HAMSTRINGS ───────────────
  {
    name: 'Romanian Deadlift',
    muscleGroup: MuscleGroup.HAMSTRINGS,
    secondaryMuscles: JSON.stringify(['GLUTES', 'BACK']),
    equipment: Equipment.GYM,
    difficulty: Difficulty.INTERMEDIATE,
    movementPattern: 'hinge',
    isCompound: true,
    contraindications: JSON.stringify(['ACUTE_LOWER_BACK_PAIN']),
    coachingCues: JSON.stringify(['Bar stays close to legs throughout', 'Hinge at hips, slight knee bend', 'Feel strong hamstring stretch', 'Drive hips forward to stand']),
    demoUrl: 'https://images.unsplash.com/photo-1605296867304-46d5465a25f1?w=500',
  },
  {
    name: 'Dumbbell Romanian Deadlift',
    muscleGroup: MuscleGroup.HAMSTRINGS,
    secondaryMuscles: JSON.stringify(['GLUTES', 'BACK']),
    equipment: Equipment.MINIMAL,
    difficulty: Difficulty.INTERMEDIATE,
    movementPattern: 'hinge',
    isCompound: true,
    contraindications: JSON.stringify(['ACUTE_LOWER_BACK_PAIN']),
    coachingCues: JSON.stringify(['Soft bend in knees, hinge backward at hips', 'Keep dumbbells close to your thighs and shins', 'Go down until you feel a hamstring stretch', 'Squeeze glutes to return to standing, avoiding back hyperextension']),
    demoUrl: 'https://images.unsplash.com/photo-1605296867304-46d5465a25f1?w=500',
  },
  {
    name: 'Lying Leg Curl',
    muscleGroup: MuscleGroup.HAMSTRINGS,
    secondaryMuscles: JSON.stringify([]),
    equipment: Equipment.GYM,
    difficulty: Difficulty.BEGINNER,
    movementPattern: 'isolation',
    isCompound: false,
    contraindications: JSON.stringify([]),
    coachingCues: JSON.stringify(['Lie face down, pad above heels', 'Curl heels toward glutes', 'Squeeze hamstrings at top', 'Lower slowly under control']),
    demoUrl: 'https://images.unsplash.com/photo-1574680096145-d05b474e2155?w=500',
  },
  {
    name: 'Seated Leg Curl',
    muscleGroup: MuscleGroup.HAMSTRINGS,
    secondaryMuscles: JSON.stringify([]),
    equipment: Equipment.GYM,
    difficulty: Difficulty.BEGINNER,
    movementPattern: 'isolation',
    isCompound: false,
    contraindications: JSON.stringify([]),
    coachingCues: JSON.stringify(['Sit with thighs on pad', 'Curl heels down and back', 'Hold at full contraction', 'Slow 3-second return']),
    demoUrl: 'https://images.unsplash.com/photo-1574680096145-d05b474e2155?w=500',
  },
  {
    name: 'Good Morning',
    muscleGroup: MuscleGroup.HAMSTRINGS,
    secondaryMuscles: JSON.stringify(['GLUTES', 'BACK']),
    equipment: Equipment.GYM,
    difficulty: Difficulty.INTERMEDIATE,
    movementPattern: 'hinge',
    isCompound: true,
    contraindications: JSON.stringify(['ACUTE_LOWER_BACK_PAIN']),
    coachingCues: JSON.stringify(['Bar on upper back', 'Slight knee bend, hinge forward', 'Keep back flat throughout', 'Drive hips forward to return']),
    demoUrl: 'https://images.unsplash.com/photo-1605296867304-46d5465a25f1?w=500',
  },
  {
    name: 'Single-Leg Romanian Deadlift',
    muscleGroup: MuscleGroup.HAMSTRINGS,
    secondaryMuscles: JSON.stringify(['GLUTES', 'ABS']),
    equipment: Equipment.MINIMAL,
    difficulty: Difficulty.INTERMEDIATE,
    movementPattern: 'hinge',
    isCompound: true,
    contraindications: JSON.stringify(['ACUTE_LOWER_BACK_PAIN']),
    coachingCues: JSON.stringify(['Balance on one leg, slight knee bend', 'Hinge forward, opposite leg extends back', 'Keep hips square to floor', 'Squeeze glute to return']),
    demoUrl: 'https://images.unsplash.com/photo-1605296867304-46d5465a25f1?w=500',
  },
  {
    name: 'Nordic Hamstring Curl',
    muscleGroup: MuscleGroup.HAMSTRINGS,
    secondaryMuscles: JSON.stringify(['GLUTES']),
    equipment: Equipment.HOME,
    difficulty: Difficulty.ADVANCED,
    movementPattern: 'hinge',
    isCompound: true,
    contraindications: JSON.stringify([]),
    coachingCues: JSON.stringify(['Partner holds ankles or anchor', 'Lower torso to floor under control', 'Use hands to catch if needed', 'Pull back up with hamstrings']),
    demoUrl: 'https://images.unsplash.com/photo-1605296867304-46d5465a25f1?w=500',
  },

  // ─────────────── GLUTES ───────────────
  {
    name: 'Barbell Hip Thrust',
    muscleGroup: MuscleGroup.GLUTES,
    secondaryMuscles: JSON.stringify(['HAMSTRINGS', 'ABS']),
    equipment: Equipment.GYM,
    difficulty: Difficulty.INTERMEDIATE,
    movementPattern: 'hinge',
    isCompound: true,
    contraindications: JSON.stringify([]),
    coachingCues: JSON.stringify(['Upper back on bench, bar over hips', 'Drive hips up squeezing glutes hard', 'Full extension — hips parallel to floor', 'Hold 1 second at the top']),
    demoUrl: 'https://images.unsplash.com/photo-1518310383802-640c2de311b2?w=500',
  },
  {
    name: 'Barbell Glute Bridge',
    muscleGroup: MuscleGroup.GLUTES,
    secondaryMuscles: JSON.stringify(['HAMSTRINGS', 'ABS']),
    equipment: Equipment.GYM,
    difficulty: Difficulty.BEGINNER,
    movementPattern: 'hinge',
    isCompound: true,
    contraindications: JSON.stringify([]),
    coachingCues: JSON.stringify(['Rest upper back on the floor, place barbell over hips', 'Drive through heels and squeeze glutes to lift hips', 'Keep your ribs down and core engaged throughout', 'Briefly pause at the top of the movement']),
    demoUrl: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=500',
  },
  {
    name: 'Bodyweight Glute Bridge',
    muscleGroup: MuscleGroup.GLUTES,
    secondaryMuscles: JSON.stringify(['HAMSTRINGS', 'ABS']),
    equipment: Equipment.HOME,
    difficulty: Difficulty.BEGINNER,
    movementPattern: 'hinge',
    isCompound: false,
    contraindications: JSON.stringify([]),
    coachingCues: JSON.stringify(['Lie on your back, knees bent, feet flat on the floor', 'Drive hips up by squeezing your glutes', 'Avoid hyperextending your lower back at the top', 'Lower under control to starting position']),
    demoUrl: 'https://images.unsplash.com/photo-1434608519344-49d77a699e1d?w=500',
  },
  {
    name: 'Frog Pump',
    muscleGroup: MuscleGroup.GLUTES,
    secondaryMuscles: JSON.stringify([]),
    equipment: Equipment.HOME,
    difficulty: Difficulty.BEGINNER,
    movementPattern: 'isolation',
    isCompound: false,
    contraindications: JSON.stringify([]),
    coachingCues: JSON.stringify(['Lie on back, soles of feet together', 'Knees out wide like a frog', 'Thrust hips up squeezing glutes', 'Lower just short of floor, repeat']),
    demoUrl: 'https://images.unsplash.com/photo-1434608519344-49d77a699e1d?w=500',
  },
  {
    name: 'Cable Glute Kickback',
    muscleGroup: MuscleGroup.GLUTES,
    secondaryMuscles: JSON.stringify(['HAMSTRINGS']),
    equipment: Equipment.GYM,
    difficulty: Difficulty.BEGINNER,
    movementPattern: 'isolation',
    isCompound: false,
    contraindications: JSON.stringify([]),
    coachingCues: JSON.stringify(['Lean slightly forward and brace core', 'Kick your leg backward, squeezing glute at peak', 'Avoid arching your lower back to get more height', 'Control the return weight with glute tension']),
    demoUrl: 'https://images.unsplash.com/photo-1518310383802-640c2de311b2?w=500',
  },
  {
    name: 'Glute Kickbacks (Banded)',
    muscleGroup: MuscleGroup.GLUTES,
    secondaryMuscles: JSON.stringify(['HAMSTRINGS']),
    equipment: Equipment.HOME,
    difficulty: Difficulty.BEGINNER,
    movementPattern: 'isolation',
    isCompound: false,
    contraindications: JSON.stringify([]),
    coachingCues: JSON.stringify(['On all fours, band above knees', 'Push foot back and up, squeezing glute', 'Avoid rotating the hip', 'Slow return for max tension']),
    demoUrl: 'https://images.unsplash.com/photo-1518310383802-640c2de311b2?w=500',
  },
  {
    name: 'Hip Abduction Machine',
    muscleGroup: MuscleGroup.GLUTES,
    secondaryMuscles: JSON.stringify([]),
    equipment: Equipment.GYM,
    difficulty: Difficulty.BEGINNER,
    movementPattern: 'isolation',
    isCompound: false,
    contraindications: JSON.stringify([]),
    coachingCues: JSON.stringify(['Sit upright, pad against outer thighs', 'Push legs out against resistance', 'Hold at full abduction 1 second', 'Slow return to center']),
    demoUrl: 'https://images.unsplash.com/photo-1518310383802-640c2de311b2?w=500',
  },
  {
    name: 'Banded Crab Walk',
    muscleGroup: MuscleGroup.GLUTES,
    secondaryMuscles: JSON.stringify(['QUADS']),
    equipment: Equipment.HOME,
    difficulty: Difficulty.BEGINNER,
    movementPattern: 'isolation',
    isCompound: false,
    contraindications: JSON.stringify([]),
    coachingCues: JSON.stringify(['Place resistance band above knees or ankles', 'Get into a quarter-squat position, chest up', 'Take controlled steps sideways, keeping tension on band', 'Do not let knees cave inward']),
    demoUrl: 'https://images.unsplash.com/photo-1518310383802-640c2de311b2?w=500',
  },

  // ─────────────── CALVES ───────────────
  {
    name: 'Standing Calf Raise',
    muscleGroup: MuscleGroup.CALVES,
    secondaryMuscles: JSON.stringify([]),
    equipment: Equipment.GYM,
    difficulty: Difficulty.BEGINNER,
    movementPattern: 'isolation',
    isCompound: false,
    contraindications: JSON.stringify([]),
    coachingCues: JSON.stringify(['Full stretch at bottom', 'Rise onto toes as high as possible', 'Hold peak for 1 second', 'Lower slowly for maximum stretch']),
    demoUrl: 'https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?w=500',
  },
  {
    name: 'Seated Calf Raise',
    muscleGroup: MuscleGroup.CALVES,
    secondaryMuscles: JSON.stringify([]),
    equipment: Equipment.MINIMAL,
    difficulty: Difficulty.BEGINNER,
    movementPattern: 'isolation',
    isCompound: false,
    contraindications: JSON.stringify([]),
    coachingCues: JSON.stringify(['Sit with knees at 90 degrees, place weight on thighs', 'Raise heels as high as possible by flexing calves', 'Hold the contraction for 1 second at top', 'Lower heels fully to get a stretch']),
    demoUrl: 'https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?w=500',
  },
  {
    name: 'Single-Leg Calf Raise',
    muscleGroup: MuscleGroup.CALVES,
    secondaryMuscles: JSON.stringify([]),
    equipment: Equipment.HOME,
    difficulty: Difficulty.BEGINNER,
    movementPattern: 'isolation',
    isCompound: false,
    contraindications: JSON.stringify([]),
    coachingCues: JSON.stringify(['Hold wall for balance', 'Rise fully onto one toe', 'Full stretch at bottom', 'Add weight for progression']),
    demoUrl: 'https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?w=500',
  },

  // ─────────────── ABS ───────────────
  {
    name: 'Cable Crunch',
    muscleGroup: MuscleGroup.ABS,
    secondaryMuscles: JSON.stringify([]),
    equipment: Equipment.GYM,
    difficulty: Difficulty.BEGINNER,
    movementPattern: 'isolation',
    isCompound: false,
    contraindications: JSON.stringify([]),
    coachingCues: JSON.stringify(['Kneel facing cable, rope at neck level', 'Crunch elbows toward knees', 'Round the back — don\'t hip hinge', 'Slow return to full extension']),
    demoUrl: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=500',
  },
  {
    name: 'Hanging Leg Raise',
    muscleGroup: MuscleGroup.ABS,
    secondaryMuscles: JSON.stringify(['OBLIQUES']),
    equipment: Equipment.GYM,
    difficulty: Difficulty.ADVANCED,
    movementPattern: 'isolation',
    isCompound: false,
    contraindications: JSON.stringify(['SHOULDER_IMPINGEMENT']),
    coachingCues: JSON.stringify(['Hang from pull-up bar', 'Raise legs to 90 degrees or higher', 'Curl pelvis up at top', 'Lower slowly with control']),
    demoUrl: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=500',
  },
  {
    name: 'Ab Wheel Rollout',
    muscleGroup: MuscleGroup.ABS,
    secondaryMuscles: JSON.stringify(['SHOULDERS', 'BACK']),
    equipment: Equipment.MINIMAL,
    difficulty: Difficulty.ADVANCED,
    movementPattern: 'isolation',
    isCompound: false,
    contraindications: JSON.stringify(['ACUTE_LOWER_BACK_PAIN']),
    coachingCues: JSON.stringify(['Start on knees, arms extended', 'Roll out as far as possible keeping back flat', 'Brace core intensely', 'Pull back with abs, not arms']),
    demoUrl: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=500',
  },
  {
    name: 'Plank',
    muscleGroup: MuscleGroup.ABS,
    secondaryMuscles: JSON.stringify(['SHOULDERS', 'QUADS']),
    equipment: Equipment.HOME,
    difficulty: Difficulty.BEGINNER,
    movementPattern: 'isolation',
    isCompound: false,
    contraindications: JSON.stringify(['ACUTE_LOWER_BACK_PAIN']),
    coachingCues: JSON.stringify(['Place forearms on floor, shoulders directly over elbows', 'Keep body in a straight, rigid line', 'Squeeze glutes and draw belly button to spine', 'Breathe regularly; do not hold your breath']),
    demoUrl: 'https://images.unsplash.com/photo-1566241477600-ac026ad43874?w=500',
  },
  {
    name: 'Hollow Body Hold',
    muscleGroup: MuscleGroup.ABS,
    secondaryMuscles: JSON.stringify([]),
    equipment: Equipment.HOME,
    difficulty: Difficulty.INTERMEDIATE,
    movementPattern: 'isolation',
    isCompound: false,
    contraindications: JSON.stringify([]),
    coachingCues: JSON.stringify(['Lie flat, press lower back into floor', 'Raise legs and shoulders off floor', 'Arms extended overhead', 'Hold as long as possible with control']),
    demoUrl: 'https://images.unsplash.com/photo-1566241477600-ac026ad43874?w=500',
  },
  {
    name: 'Dead Bug',
    muscleGroup: MuscleGroup.ABS,
    secondaryMuscles: JSON.stringify([]),
    equipment: Equipment.HOME,
    difficulty: Difficulty.BEGINNER,
    movementPattern: 'isolation',
    isCompound: false,
    contraindications: JSON.stringify([]),
    coachingCues: JSON.stringify(['Lie flat on back, arms extended up, knees at 90 degrees', 'Lower opposite arm and leg toward floor, keeping back flat', 'Press lower back firmly into the floor (no space)', 'Return to starting position and switch sides']),
    demoUrl: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=500',
  },
  {
    name: 'Bicycle Crunches',
    muscleGroup: MuscleGroup.ABS,
    secondaryMuscles: JSON.stringify(['OBLIQUES']),
    equipment: Equipment.HOME,
    difficulty: Difficulty.BEGINNER,
    movementPattern: 'isolation',
    isCompound: false,
    contraindications: JSON.stringify(['NECK_PAIN']),
    coachingCues: JSON.stringify(['Lie flat, hands behind head, legs lifted in tabletop', 'Bring elbow to opposite knee while extending other leg', 'Rotate shoulders and engage obliques, not pulling neck', 'Perform slow, controlled rotations']),
    demoUrl: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=500',
  },
  {
    name: 'Bird Dog',
    muscleGroup: MuscleGroup.ABS,
    secondaryMuscles: JSON.stringify(['GLUTES', 'BACK']),
    equipment: Equipment.HOME,
    difficulty: Difficulty.BEGINNER,
    movementPattern: 'isolation',
    isCompound: false,
    contraindications: JSON.stringify([]),
    coachingCues: JSON.stringify(['Start on hands and knees (tabletop position)', 'Reach one arm forward and opposite leg straight back', 'Keep hips square and parallel to the floor', 'Avoid arching your lower back']),
    demoUrl: 'https://images.unsplash.com/photo-1566241477600-ac026ad43874?w=500',
  },

  // ─────────────── OBLIQUES ───────────────
  {
    name: 'Russian Twist',
    muscleGroup: MuscleGroup.OBLIQUES,
    secondaryMuscles: JSON.stringify(['ABS']),
    equipment: Equipment.HOME,
    difficulty: Difficulty.BEGINNER,
    movementPattern: 'isolation',
    isCompound: false,
    contraindications: JSON.stringify(['ACUTE_LOWER_BACK_PAIN']),
    coachingCues: JSON.stringify(['Sit at 45 degrees, feet off floor', 'Rotate torso side to side', 'Keep chest up, don\'t round back', 'Add weight for progression']),
    demoUrl: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=500',
  },
  {
    name: 'Cable Woodchopper',
    muscleGroup: MuscleGroup.OBLIQUES,
    secondaryMuscles: JSON.stringify(['ABS', 'SHOULDERS']),
    equipment: Equipment.GYM,
    difficulty: Difficulty.INTERMEDIATE,
    movementPattern: 'isolation',
    isCompound: false,
    contraindications: JSON.stringify(['ACUTE_LOWER_BACK_PAIN']),
    coachingCues: JSON.stringify(['Cable set high, pull diagonally across body', 'Rotate through hips and torso', 'Arms stay extended throughout', 'Control the return']),
    demoUrl: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=500',
  },
  {
    name: 'Side Plank',
    muscleGroup: MuscleGroup.OBLIQUES,
    secondaryMuscles: JSON.stringify(['ABS', 'SHOULDERS']),
    equipment: Equipment.HOME,
    difficulty: Difficulty.BEGINNER,
    movementPattern: 'isolation',
    isCompound: false,
    contraindications: JSON.stringify(['SHOULDER_IMPINGEMENT']),
    coachingCues: JSON.stringify(['Forearm on floor, body in straight line', 'Drive hips up, squeeze oblique', 'Don\'t let hips sag', 'Hold for time or add raises']),
    demoUrl: 'https://images.unsplash.com/photo-1566241477600-ac026ad43874?w=500',
  },
];

async function main() {
  console.log('🌱 Seeding exercise library...');
  let created = 0;
  let updated = 0;

  for (const ex of exercises) {
    const result = await prisma.exercise.upsert({
      where: { name: ex.name },
      create: ex,
      update: {
        muscleGroup: ex.muscleGroup,
        secondaryMuscles: ex.secondaryMuscles,
        equipment: ex.equipment,
        difficulty: ex.difficulty,
        movementPattern: ex.movementPattern,
        isCompound: ex.isCompound,
        contraindications: ex.contraindications,
        coachingCues: ex.coachingCues,
        demoUrl: ex.demoUrl,
      },
    });
    if (result) {
      const isNew = result.name === ex.name;
      created++;
    }
  }

  console.log(`✅ Seeded ${exercises.length} exercises into the library.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
